/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rezervari_status": {
    get: {
      parameters: {
        query: {
          status?: parameters["rowFilter.rezervari_status.status"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rezervari_status"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** rezervari_status */
          rezervari_status?: definitions["rezervari_status"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          status?: parameters["rowFilter.rezervari_status.status"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          status?: parameters["rowFilter.rezervari_status.status"];
        };
        body: {
          /** rezervari_status */
          rezervari_status?: definitions["rezervari_status"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/member_types": {
    get: {
      parameters: {
        query: {
          type?: parameters["rowFilter.member_types.type"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["member_types"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** member_types */
          member_types?: definitions["member_types"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          type?: parameters["rowFilter.member_types.type"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          type?: parameters["rowFilter.member_types.type"];
        };
        body: {
          /** member_types */
          member_types?: definitions["member_types"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          active?: parameters["rowFilter.profiles.active"];
          member_type?: parameters["rowFilter.profiles.member_type"];
          /** Cine are cheie de la sala */
          has_key?: parameters["rowFilter.profiles.has_key"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          active?: parameters["rowFilter.profiles.active"];
          member_type?: parameters["rowFilter.profiles.member_type"];
          /** Cine are cheie de la sala */
          has_key?: parameters["rowFilter.profiles.has_key"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          active?: parameters["rowFilter.profiles.active"];
          member_type?: parameters["rowFilter.profiles.member_type"];
          /** Cine are cheie de la sala */
          has_key?: parameters["rowFilter.profiles.has_key"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/mese": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.mese.id"];
          name?: parameters["rowFilter.mese.name"];
          location?: parameters["rowFilter.mese.location"];
          type?: parameters["rowFilter.mese.type"];
          color?: parameters["rowFilter.mese.color"];
          has_robot?: parameters["rowFilter.mese.has_robot"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["mese"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** mese */
          mese?: definitions["mese"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.mese.id"];
          name?: parameters["rowFilter.mese.name"];
          location?: parameters["rowFilter.mese.location"];
          type?: parameters["rowFilter.mese.type"];
          color?: parameters["rowFilter.mese.color"];
          has_robot?: parameters["rowFilter.mese.has_robot"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.mese.id"];
          name?: parameters["rowFilter.mese.name"];
          location?: parameters["rowFilter.mese.location"];
          type?: parameters["rowFilter.mese.type"];
          color?: parameters["rowFilter.mese.color"];
          has_robot?: parameters["rowFilter.mese.has_robot"];
        };
        body: {
          /** mese */
          mese?: definitions["mese"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rezervari": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rezervari.id"];
          created_at?: parameters["rowFilter.rezervari.created_at"];
          user_id?: parameters["rowFilter.rezervari.user_id"];
          table_id?: parameters["rowFilter.rezervari.table_id"];
          start_date?: parameters["rowFilter.rezervari.start_date"];
          status?: parameters["rowFilter.rezervari.status"];
          start_hour?: parameters["rowFilter.rezervari.start_hour"];
          duration?: parameters["rowFilter.rezervari.duration"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rezervari"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** rezervari */
          rezervari?: definitions["rezervari"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rezervari.id"];
          created_at?: parameters["rowFilter.rezervari.created_at"];
          user_id?: parameters["rowFilter.rezervari.user_id"];
          table_id?: parameters["rowFilter.rezervari.table_id"];
          start_date?: parameters["rowFilter.rezervari.start_date"];
          status?: parameters["rowFilter.rezervari.status"];
          start_hour?: parameters["rowFilter.rezervari.start_hour"];
          duration?: parameters["rowFilter.rezervari.duration"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rezervari.id"];
          created_at?: parameters["rowFilter.rezervari.created_at"];
          user_id?: parameters["rowFilter.rezervari.user_id"];
          table_id?: parameters["rowFilter.rezervari.table_id"];
          start_date?: parameters["rowFilter.rezervari.start_date"];
          status?: parameters["rowFilter.rezervari.status"];
          start_hour?: parameters["rowFilter.rezervari.start_hour"];
          duration?: parameters["rowFilter.rezervari.duration"];
        };
        body: {
          /** rezervari */
          rezervari?: definitions["rezervari"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/locations": {
    get: {
      parameters: {
        query: {
          name?: parameters["rowFilter.locations.name"];
          reservation_duration?: parameters["rowFilter.locations.reservation_duration"];
          max_reservations?: parameters["rowFilter.locations.max_reservations"];
          start_hour?: parameters["rowFilter.locations.start_hour"];
          end_hour?: parameters["rowFilter.locations.end_hour"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["locations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** locations */
          locations?: definitions["locations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          name?: parameters["rowFilter.locations.name"];
          reservation_duration?: parameters["rowFilter.locations.reservation_duration"];
          max_reservations?: parameters["rowFilter.locations.max_reservations"];
          start_hour?: parameters["rowFilter.locations.start_hour"];
          end_hour?: parameters["rowFilter.locations.end_hour"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          name?: parameters["rowFilter.locations.name"];
          reservation_duration?: parameters["rowFilter.locations.reservation_duration"];
          max_reservations?: parameters["rowFilter.locations.max_reservations"];
          start_hour?: parameters["rowFilter.locations.start_hour"];
          end_hour?: parameters["rowFilter.locations.end_hour"];
        };
        body: {
          /** locations */
          locations?: definitions["locations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/create_reservation": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: date */
            start_date_input: string;
            /** Format: smallint */
            start_hour_input: number;
            /** Format: uuid */
            table_id_input: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  rezervari_status: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    status: string;
  };
  member_types: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    type: string;
  };
  profiles: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    name: string;
    /**
     * Format: boolean
     * @default true
     */
    active?: boolean;
    /**
     * Format: text
     * @description Note:
     * This is a Foreign Key to `member_types.type`.<fk table='member_types' column='type'/>
     * @default Membru
     */
    member_type?: string;
    /**
     * Format: boolean
     * @description Cine are cheie de la sala
     * @default false
     */
    has_key?: boolean;
  };
  mese: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    name: string;
    /**
     * Format: text
     * @description Note:
     * This is a Foreign Key to `locations.name`.<fk table='locations' column='name'/>
     */
    location: string;
    /** Format: text */
    type: string;
    /** Format: text */
    color: string;
    /**
     * Format: boolean
     * @default false
     */
    has_robot: boolean;
  };
  rezervari: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /** Format: uuid */
    user_id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `mese.id`.<fk table='mese' column='id'/>
     */
    table_id: string;
    /** Format: date */
    start_date: string;
    /**
     * Format: text
     * @description Note:
     * This is a Foreign Key to `rezervari_status.status`.<fk table='rezervari_status' column='status'/>
     */
    status: string;
    /** Format: smallint */
    start_hour: number;
    /** Format: smallint */
    duration: number;
  };
  /** @description Locatiile fizice unde se pot face rezervari (de ex. gara, boromir) */
  locations: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    name: string;
    /** Format: smallint */
    reservation_duration: number;
    /** Format: smallint */
    max_reservations: number;
    /** Format: smallint */
    start_hour: number;
    /** Format: smallint */
    end_hour: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description rezervari_status */
  "body.rezervari_status": definitions["rezervari_status"];
  /** Format: text */
  "rowFilter.rezervari_status.status": string;
  /** @description member_types */
  "body.member_types": definitions["member_types"];
  /** Format: text */
  "rowFilter.member_types.type": string;
  /** @description profiles */
  "body.profiles": definitions["profiles"];
  /** Format: uuid */
  "rowFilter.profiles.id": string;
  /** Format: text */
  "rowFilter.profiles.name": string;
  /** Format: boolean */
  "rowFilter.profiles.active": string;
  /** Format: text */
  "rowFilter.profiles.member_type": string;
  /**
   * Format: boolean
   * @description Cine are cheie de la sala
   */
  "rowFilter.profiles.has_key": string;
  /** @description mese */
  "body.mese": definitions["mese"];
  /** Format: uuid */
  "rowFilter.mese.id": string;
  /** Format: text */
  "rowFilter.mese.name": string;
  /** Format: text */
  "rowFilter.mese.location": string;
  /** Format: text */
  "rowFilter.mese.type": string;
  /** Format: text */
  "rowFilter.mese.color": string;
  /** Format: boolean */
  "rowFilter.mese.has_robot": string;
  /** @description rezervari */
  "body.rezervari": definitions["rezervari"];
  /** Format: uuid */
  "rowFilter.rezervari.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.rezervari.created_at": string;
  /** Format: uuid */
  "rowFilter.rezervari.user_id": string;
  /** Format: uuid */
  "rowFilter.rezervari.table_id": string;
  /** Format: date */
  "rowFilter.rezervari.start_date": string;
  /** Format: text */
  "rowFilter.rezervari.status": string;
  /** Format: smallint */
  "rowFilter.rezervari.start_hour": string;
  /** Format: smallint */
  "rowFilter.rezervari.duration": string;
  /** @description locations */
  "body.locations": definitions["locations"];
  /** Format: text */
  "rowFilter.locations.name": string;
  /** Format: smallint */
  "rowFilter.locations.reservation_duration": string;
  /** Format: smallint */
  "rowFilter.locations.max_reservations": string;
  /** Format: smallint */
  "rowFilter.locations.start_hour": string;
  /** Format: smallint */
  "rowFilter.locations.end_hour": string;
}

export interface operations {}

export interface external {}
