/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rezervari_status": {
    get: {
      parameters: {
        query: {
          status?: parameters["rowFilter.rezervari_status.status"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rezervari_status"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** rezervari_status */
          rezervari_status?: definitions["rezervari_status"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          status?: parameters["rowFilter.rezervari_status.status"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          status?: parameters["rowFilter.rezervari_status.status"];
        };
        body: {
          /** rezervari_status */
          rezervari_status?: definitions["rezervari_status"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/mese": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.mese.id"];
          created_at?: parameters["rowFilter.mese.created_at"];
          name?: parameters["rowFilter.mese.name"];
          color?: parameters["rowFilter.mese.color"];
          location?: parameters["rowFilter.mese.location"];
          type?: parameters["rowFilter.mese.type"];
          has_robot?: parameters["rowFilter.mese.has_robot"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["mese"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** mese */
          mese?: definitions["mese"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.mese.id"];
          created_at?: parameters["rowFilter.mese.created_at"];
          name?: parameters["rowFilter.mese.name"];
          color?: parameters["rowFilter.mese.color"];
          location?: parameters["rowFilter.mese.location"];
          type?: parameters["rowFilter.mese.type"];
          has_robot?: parameters["rowFilter.mese.has_robot"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.mese.id"];
          created_at?: parameters["rowFilter.mese.created_at"];
          name?: parameters["rowFilter.mese.name"];
          color?: parameters["rowFilter.mese.color"];
          location?: parameters["rowFilter.mese.location"];
          type?: parameters["rowFilter.mese.type"];
          has_robot?: parameters["rowFilter.mese.has_robot"];
        };
        body: {
          /** mese */
          mese?: definitions["mese"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rezervari": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rezervari.id"];
          created_at?: parameters["rowFilter.rezervari.created_at"];
          table_id?: parameters["rowFilter.rezervari.table_id"];
          user_id?: parameters["rowFilter.rezervari.user_id"];
          start_date?: parameters["rowFilter.rezervari.start_date"];
          duration?: parameters["rowFilter.rezervari.duration"];
          status?: parameters["rowFilter.rezervari.status"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rezervari"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** rezervari */
          rezervari?: definitions["rezervari"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rezervari.id"];
          created_at?: parameters["rowFilter.rezervari.created_at"];
          table_id?: parameters["rowFilter.rezervari.table_id"];
          user_id?: parameters["rowFilter.rezervari.user_id"];
          start_date?: parameters["rowFilter.rezervari.start_date"];
          duration?: parameters["rowFilter.rezervari.duration"];
          status?: parameters["rowFilter.rezervari.status"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rezervari.id"];
          created_at?: parameters["rowFilter.rezervari.created_at"];
          table_id?: parameters["rowFilter.rezervari.table_id"];
          user_id?: parameters["rowFilter.rezervari.user_id"];
          start_date?: parameters["rowFilter.rezervari.start_date"];
          duration?: parameters["rowFilter.rezervari.duration"];
          status?: parameters["rowFilter.rezervari.status"];
        };
        body: {
          /** rezervari */
          rezervari?: definitions["rezervari"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/locations": {
    get: {
      parameters: {
        query: {
          name?: parameters["rowFilter.locations.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["locations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** locations */
          locations?: definitions["locations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          name?: parameters["rowFilter.locations.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          name?: parameters["rowFilter.locations.name"];
        };
        body: {
          /** locations */
          locations?: definitions["locations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  rezervari_status: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    status: string;
  };
  profiles: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    name: string;
  };
  mese: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /** Format: text */
    name: string;
    /** Format: text */
    color: string;
    /**
     * Format: text
     * @description Note:
     * This is a Foreign Key to `locations.name`.<fk table='locations' column='name'/>
     */
    location: string;
    /** Format: text */
    type: string;
    /**
     * Format: boolean
     * @default false
     */
    has_robot: boolean;
  };
  rezervari: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `mese.id`.<fk table='mese' column='id'/>
     */
    table_id: number;
    /** Format: uuid */
    user_id: string;
    /** Format: timestamp with time zone */
    start_date: string;
    /** Format: integer */
    duration: number;
    /**
     * Format: text
     * @description Note:
     * This is a Foreign Key to `rezervari_status.status`.<fk table='rezervari_status' column='status'/>
     * @default pending
     */
    status: string;
  };
  /** @description Locatiile fizice unde se pot face rezervari (de ex. gara, boromir) */
  locations: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    name: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description rezervari_status */
  "body.rezervari_status": definitions["rezervari_status"];
  /** Format: text */
  "rowFilter.rezervari_status.status": string;
  /** @description profiles */
  "body.profiles": definitions["profiles"];
  /** Format: uuid */
  "rowFilter.profiles.id": string;
  /** Format: text */
  "rowFilter.profiles.name": string;
  /** @description mese */
  "body.mese": definitions["mese"];
  /** Format: bigint */
  "rowFilter.mese.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.mese.created_at": string;
  /** Format: text */
  "rowFilter.mese.name": string;
  /** Format: text */
  "rowFilter.mese.color": string;
  /** Format: text */
  "rowFilter.mese.location": string;
  /** Format: text */
  "rowFilter.mese.type": string;
  /** Format: boolean */
  "rowFilter.mese.has_robot": string;
  /** @description rezervari */
  "body.rezervari": definitions["rezervari"];
  /** Format: uuid */
  "rowFilter.rezervari.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.rezervari.created_at": string;
  /** Format: bigint */
  "rowFilter.rezervari.table_id": string;
  /** Format: uuid */
  "rowFilter.rezervari.user_id": string;
  /** Format: timestamp with time zone */
  "rowFilter.rezervari.start_date": string;
  /** Format: integer */
  "rowFilter.rezervari.duration": string;
  /** Format: text */
  "rowFilter.rezervari.status": string;
  /** @description locations */
  "body.locations": definitions["locations"];
  /** Format: text */
  "rowFilter.locations.name": string;
}

export interface operations {}

export interface external {}
